version: 2
project_name: qv

before:
  hooks:
    - go mod tidy

builds:
  - id: qv
    main: ./main.go
    binary: qv
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: archives
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: qv
    repository:
      owner: shivgitcode
      name: homebrew-tap
      branch: main
    commit_author:
      name: Shivansh Agarwal
      email: shivneeraj2004@gmail.com
    description: "A CLI tool for quick variable management"
    homepage: "https://github.com/shivgitcode/qv"
    license: MIT
    directory: Formula
    install: |
      bin.install "qv"
    test: |
      system "#{bin}/qv"

scoops:
  - name: qv
    repository:
      owner: shivgitcode
      name: scoop-bucket
      branch: main
    commit_author:
      name: Shivansh Agarwal
      email: you@example.com
    homepage: "https://github.com/shivgitcode/qv"
    description: "A CLI tool for quick variable management"
    license: MIT

nfpms:
  - id: packages
    package_name: qv
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    maintainer: "Shivansh Agarwal shivneeraj2004@gmail.com"
    description: "A CLI tool for quick variable management"
    homepage: "https://github.com/shivgitcode/qv"
    license: MIT
    section: utils
    priority: extra
    bindir: /usr/local/bin
    formats:
      - deb
      - rpm
      - apk

release:
  github:
    owner: shivgitcode
    name: qv
  draft: false
  prerelease: false
